ALTER TABLE `games` CHANGE `stream_name` `streamer_name` VARCHAR(31);

CREATE TABLE IF NOT EXISTS `games` (
  `id`                BIGINT(20) NOT NULL AUTO_INCREMENT,
  `type`              VARCHAR(31),
  `streamer_name`     VARCHAR(127),
  `blue_player1_name` VARCHAR(31),
  `blue_player1_info` MEDIUMTEXT,
  `blue_player2_name` VARCHAR(31),
  `blue_player2_info` MEDIUMTEXT,
  `blue_player3_name` VARCHAR(31),
  `blue_player3_info` MEDIUMTEXT,
  `blue_player4_name` VARCHAR(31),
  `blue_player4_info` MEDIUMTEXT,
  `blue_player5_name` VARCHAR(31),
  `blue_player5_info` MEDIUMTEXT,
  `red_player1_name`  VARCHAR(31),
  `red_player1_info`  MEDIUMTEXT,
  `red_player2_name`  VARCHAR(31),
  `red_player2_info`  MEDIUMTEXT,
  `red_player3_name`  VARCHAR(31),
  `red_player3_info`  MEDIUMTEXT,
  `red_player4_name`  VARCHAR(31),
  `red_player4_info`  MEDIUMTEXT,
  `red_player5_name`  VARCHAR(31),
  `red_player5_info`  MEDIUMTEXT,
  `won`               BOOLEAN,
  `start_time`        TIMESTAMP DEFAULT 0,
  `end_time`          TIMESTAMP DEFAULT 0,
  `length`            INT,
  `other`             MEDIUMTEXT,
  `filler1`           VARCHAR(127),
  `filler2`           VARCHAR(127),
  `filler3`           VARCHAR(127),
  `filler4`           VARCHAR(127),
  `filler5`           VARCHAR(127),
  `filler6`           VARCHAR(127),
  `filler7`           VARCHAR(127),
  `filler8`           VARCHAR(127),
  `filler9`           VARCHAR(127),
  `filler10`          VARCHAR(127),

  PRIMARY KEY (`id`),
  UNIQUE INDEX (`streamer_name`, `start_time`),
  KEY `games_streamer_name` (`streamer_name`),
  KEY `games_start_time` (`start_time`),
  KEY `games_end_time` (`end_time`)
)
  ENGINE =InnoDB
  DEFAULT CHARSET =utf8
  COLLATE =utf8_unicode_ci;